version: '3'

services:
  postgres:
    build:
      context: "./docker file psql"  # Ruta al directorio que contiene el Dockerfile
    container_name: THE_POSTGRESQL_CONTAINER
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
